title: CSCI-UA.0480 Fall 2019, Section 003

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

vars:
  piazza: "https://piazza.com/class/jzu453hfwul1qr"
  email: "jversoza at cs dot nyu dot edu"
  slides_img_prefix: "../../resources/img"
  
  # course
  course_number: "CSCI-UA.0480"
  course_section: "003"
  course_name: "Data Management and Analysis"
  course_semester: "Fall 2019"
  course_time: "T and TH, 11:00-12:15PM"
  course_room: "60 5th Ave, Room 110"
  course_site: https://cs.nyu.edu/courses/fall19/CSCI-UA.0480-003/ 
  course_site_alt: http://cs.nyu.edu/~jversoza
  
  # office hours
  office_hours: "<br>Mon/Wed 11:25am - 12:25pm at WWH 422<br>Thurs 12:15pm - 1:15pm at 60 5th Ave lobby"
  office_hours_room: WWH 422 on Mon/Wed... Lobby, 60 5th Ave on Thurs
  
  # midterm
  midterm1_date: "N/A"
  midterm1_time: "N/A"
  
  # finals
  final_date: "N/A"
  final_time: "N/A"
  final_room: "N/A"
  
  
  book1: "Python for Data Analysis Book, 2nd Edition"
  book1_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/python-for-data/9781491957653/"
  book1_author: "Wes McKinney"

  book2: "Practical SQL"
  book2_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/practical-sql/9781492067580/"
  book2_author:  "Anthony DeBarros"
  
  book3: "Think Stats"
  book3_link: "http://greenteapress.com/thinkstats/"
  book3_author: "Allen B. Downey"

  book4: "Data Science from Scratch, 2nd Edition"
  book4_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/data-science-from/9781492041122/"
  book4_author: "Joel Grus"
  
  book5: "Relational Database Design and Implementation, 3rd Edition"
  book5_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/relational-database-design/9780123747303/"
  book5_author: "Jan L. Harrington"
